### ISSUE TITLE
没处理只有当天报告的情况

### ISSUE THREAD

**Issue by Tiacx** [tree-branch/new_house#1]
第一次运行，只有一个报告的时候，没法查看报告；

**Comment by tree-branch** [comment]
嗯，确实第一天没有报告这是事，大家都挺介意。我这有空的时候改成
相较于空的昨天数据来处理吧。你要是能帮我改好就更感谢了。如果你着急的话可以联系我催我一下

**Comment by Tiacx** [comment]
> 嗯，确实第一天没有报告这是事，大家都挺介意。我这有空的时候改成
> 相较于空的昨天数据来处理吧。你要是能帮我改好就更感谢了。如果你着急的话可以联系我催我一下

不着急，我只是随便看一下，我暂时先改成下面这样了
``` python
if data1 is None:
    data1, day1 = (data0, 0)
```
